# Generated by Django 3.2.14 on 2022-11-16 05:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('obb_app', '0002_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ManyToManyField(related_name='fk_sd_m2m_bus', to='obb_app.Bus')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ds_destination', to='obb_app.route')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ds_source', to='obb_app.route')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ds_via', to='obb_app.route')),
            ],
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('occupied', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_bs_bus', to='obb_app.bus')),
            ],
        ),
    ]
