# Generated by Django 3.2.14 on 2022-11-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obb_app', '0003_busseat_dailyschedule_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busseat',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='dailyschedule',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterUniqueTogether(
            name='busseat',
            unique_together={('bus', 'name')},
        ),
    ]
