# Generated by Django 3.2.14 on 2022-11-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obb_app', '0006_alter_busseat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busseat',
            options={'ordering': ['name']},
        ),
    ]
