# Generated by Django 3.2.14 on 2022-11-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obb_app', '0007_alter_busseat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
