# Generated by Django 3.2.14 on 2022-11-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obb_app', '0008_dailyschedule_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busseat',
            name='occupied',
        ),
    ]
