# Generated by Django 3.2.14 on 2022-11-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obb_app', '0009_remove_busseat_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
