# Generated by Django 3.2.14 on 2022-11-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obb_app', '0011_auto_20221122_0738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingSeats',
        ),
    ]
