# Generated by Django 3.2.14 on 2022-11-22 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obb_app', '0012_delete_bookingseats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'time')},
        ),
    ]
