# Generated by Django 3.2.14 on 2022-11-22 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obb_app', '0013_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='datetime_paid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
