# Generated by Django 3.2.14 on 2022-11-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obb_app', '0015_alter_booking_datetime_paid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'time', 'seat_person')},
        ),
    ]
